version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/notification_db
      - RABBITMQ_HOST=rabbitmq

volumes:
  mongo_data:
